### PR TITLE
Fix requestheader-allowed-names header

### PR DESCRIPTION
**Pull request by erkanerol**
Towards https://github.com/giantswarm/giantswarm/issues/23276

### Testing

- [x] Fresh install works.
- [x] Upgrade from previous version works.

### Checklist

- [x] Update changelog in `CHANGELOG.md`.
- [x] Make sure `values.yaml` is valid.

### CODE REVIEW

**Comment by erkanerol** [comment]
I will test this PR in an MC to ensure all apps are OK with this config.

**Comment by kopiczko** [comment]
Do you have some link or explanation why this is required?

**Comment by erkanerol** [comment]
I tested this PR in gamma. It is OK.

**Comment by erkanerol** [comment]
@kopiczko  I am not 100% sure. Actually, this is the default configuration of CAPO.

```
- --requestheader-allowed-names=front-proxy-client
- --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
```

I updated this part by using vintage configuration but I guess PKI part is different here. This chart explains the mechanism
https://d33wubrfki0l68.cloudfront.net/3c5428678a95c3715894011d8dd4812d2cf229b9/e745c/images/docs/aggregation-api-auth-flow.png

I also found this https://github.com/kubernetes-sigs/metrics-server/blob/master/KNOWN_ISSUES.md#incorrectly-configured-front-proxy-certificate In our setup, I didn't need to change anything in metrics-server configuration for certificates. Here are the flags we use

```
        - name: metrics-server
          args:
          - "--logtostderr"
          - "--kubelet-insecure-tls"
          - "--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname"
          - "--kubelet-use-node-status-port"
          - "--cert-dir=/tmp"
          - "--secure-port=10443"
```

**Review by kopiczko — APPROVED** [review]

**Pull request merged**
